

/*•	Cantidad de lavadoras que se encuentran en: Buen Estado, Mal Estado, De Baja.*/

SELECT
      LAVADORA.LAVADORA_ID AS ID,
      LAVADORA.LAVADORA_DESCRIP AS LAVADORA,
      ESTADO_LAVADORA.ESTADO_LAV_NOMBRE AS ESTADO
FROM ESTADO_LAVADORA
INNER JOIN LAVADORA ON LAVADORA.ESTADO_LAV_ID = ESTADO_LAVADORA.ESTADO_LAV_ID
GROUP BY ID
ORDER BY ESTADO_LAVADORA.ESTADO_LAV_ID ASC