

/*•	Mostrar cuantos mantenimientos ha realizado cada técnico*/
SELECT
      EMPLEADO.EMPLEADO_ID AS ID,
      CONCAT(EMPLEADO.EMPLEADO_NOMBRE,' ',EMPLEADO.EMPLEADO_APELLIDOS) as Empleado,
      TIPO_EMPLEADO.TIPO_EMPLEADO_NOMBRE AS Tipo,
      COUNT(MANTENIMIENTO.EMPLEADO_ID) as NumerosMantenimientos
FROM EMPLEADO
INNER JOIN TIPO_EMPLEADO on TIPO_EMPLEADO.TIPO_EMPLEADO_ID = EMPLEADO.TIPO_EMPLEADO_ID
INNER JOIN MANTENIMIENTO on EMPLEADO.EMPLEADO_ID = MANTENIMIENTO.EMPLEADO_ID
GROUP BY Tipo, ID
ORDER BY NumerosMantenimientos DESC