

/*•	Cantidad de lavadoras que se encuentran en: Buen Estado, Mal Estado, De Baja.*/

SELECT
      ESTADO_LAVADORA.ESTADO_LAV_ID AS ID,
      ESTADO_LAVADORA.ESTADO_LAV_NOMBRE as EstadoNombre,
      COUNT(LAVADORA.ESTADO_LAV_ID) AS Cantidad
FROM ESTADO_LAVADORA
INNER JOIN LAVADORA ON LAVADORA.ESTADO_LAV_ID = ESTADO_LAVADORA.ESTADO_LAV_ID
GROUP BY EstadoNombre
ORDER BY ID ASC